config:
  # MkDocs (Python-Markdown) expects 4-space indentation for nested list items.
  MD007:
    indent: 4
  # MD046 (code-block-style) does not understand MkDocs/Material directives like `!!! admonition`,
  # and can mis-detect their indented bodies as "indented code blocks". Keep it disabled to avoid
  # false positives.
  MD046: false
  # Snippet files under docs/_snippets/ are not standalone documents and frequently start with an
  # admonition rather than an H1.
  MD041: false
  # Enforce consistent table formatting. We prefer aligned tables (readable diffs, aligned columns).
  MD060:
    style: aligned
  # Match our docs style: allow up to 120 chars per line.
  MD013:
    line_length: 120
    code_blocks: false
    tables: true
