name: "Bug report"
description: Report a problem with the compiler, tooling, runtime, or docs behavior.
title: "bug - "
type: Bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please include a minimal reproduction when possible.
  - type: dropdown
    id: area
    attributes:
      label: Area
      multiple: true
      options:
        - Incan Language (syntax/semantics)
        - Compiler (frontend/backend/codegen)
        - Tooling (CLI/formatter/test runner)
        - Editor integration (LSP/VS Code extension)
        - Runtime / Core crates (stdlib/core/derive)
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened, and what did you expect to happen?
      placeholder: |
        Expected: ...
        Actual: ...
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal code/sample and commands to reproduce.
      placeholder: |
        1) ...
        2) ...
        3) ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Output / logs
      description: Paste compiler output, stack traces, or relevant logs.
      render: text
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Rust version, Incan commit/version, and any relevant tooling.
      placeholder: |
        OS:
        Rust:
        Incan:
        Command:
    validations:
      required: true


