name: "Chore / maintenance"
description: Refactors, cleanup, dependency bumps, CI improvements, and other non-feature work.
title: "chore - "
type: Chore
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      multiple: true
      options:
        - Incan Language (syntax/semantics)
        - Compiler (frontend/backend/codegen)
        - Tooling (CLI/formatter/test runner)
        - Editor integration (LSP/VS Code extension)
        - Runtime / Core crates (stdlib/core/derive)
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What maintenance work is needed and why?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      placeholder: |
        - In scope:
        - Out of scope:
        - Risks:
    validations:
      required: true
  - type: textarea
    id: plan
    attributes:
      label: Plan
      description: Steps you expect to take; include affected modules/files if known.
  - type: textarea
    id: done
    attributes:
      label: Done when
      description: Concrete acceptance criteria / checks.


