name: "Documentation"
description: Report missing, confusing, or incorrect documentation; propose doc improvements.
labels: ["documentation"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What’s wrong or missing? What did you expect to find?
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Location(s)
      description: Where is the issue? Link to files/sections/pages.
      placeholder: |
        - README.md: ...
        - docs/...: ...
    validations:
      required: true
  - type: dropdown
    id: doc_type
    attributes:
      label: Doc type (Divio)
      description: What kind of doc should this be?
      options:
        - Tutorial
        - How-to guide
        - Reference
        - Explanation
        - Not sure
    validations:
      required: true
  - type: dropdown
    id: audience
    attributes:
      label: Audience
      options:
        - Language user (writing .incn)
        - Tooling user (CLI/editor/LSP/fmt/test)
        - Contributor (compiler/crates/RFCs)
        - Not sure
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed change (optional)
      description: If you have a suggested wording or structure, drop it here.


