name: "Feature request"
description: Propose a new language feature, tooling improvement, or enhancement.
title: "feature - "
type: Feature
labels: ["feature"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      multiple: true
      options:
        - Incan Language (syntax/semantics)
        - Compiler (frontend/backend/codegen)
        - Tooling (CLI/formatter/test runner)
        - Editor integration (LSP/VS Code extension)
        - Runtime / Core crates (stdlib/core/derive)
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve? What’s painful today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see? Include examples (Incan code) if helpful.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other ways to solve it (including “do nothing”).
  - type: textarea
    id: scope
    attributes:
      label: Scope / acceptance criteria
      description: What’s included, what’s not, and how we know it’s done.
      placeholder: |
        - In scope:
        - Out of scope:
        - Done when:
