name: "RFC proposal"
description: Propose a significant language/tooling change that should go through the RFC process.
labels: ["RFC"]
body:
  - type: markdown
    attributes:
      value: |
        Use this issue to propose an RFC topic and get early alignment.
        If accepted, we’ll typically ask for a PR adding an RFC document under `docs/RFCs/` based on the RFC template.
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Language (syntax/semantics)
        - Type system
        - Tooling / CLI
        - Stdlib / Runtime crates
        - LSP / Editor integration
        - Other
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One-paragraph overview of the change and why it matters.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve? Who benefits? Why now?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal sketch
      description: Syntax/examples, expected behavior, and key design constraints.
      placeholder: |
        Examples:
        ```incan
        # ...
        ```
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other plausible designs and why they’re worse.
  - type: textarea
    id: impact
    attributes:
      label: Impact / compatibility
      description: Breaking changes, migration story, performance/runtime implications.
  - type: textarea
    id: implementation
    attributes:
      label: Implementation notes (optional)
      description: Which layers likely change (frontend/backend/stdlib/tooling), and testing strategy.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I checked for an existing RFC/issue covering this.
          required: true
        - label: I can describe how this impacts existing code and how to migrate (if needed).
          required: false
